# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gameslot.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gameslot.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0egameslot.proto\"\"\n\x10Slot_Object_Ping\x12\x0e\n\x06run_id\x18\x01 \x01(\x05\"\"\n\x10Slot_Object_Pong\x12\x0e\n\x06run_id\x18\x01 \x01(\x05\x32P\n\x0fGameSlotService\x12=\n\x13obtenir_slot_object\x12\x11.Slot_Object_Ping\x1a\x11.Slot_Object_Pong\"\x00\x62\x06proto3'
)




_SLOT_OBJECT_PING = _descriptor.Descriptor(
  name='Slot_Object_Ping',
  full_name='Slot_Object_Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='run_id', full_name='Slot_Object_Ping.run_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=52,
)


_SLOT_OBJECT_PONG = _descriptor.Descriptor(
  name='Slot_Object_Pong',
  full_name='Slot_Object_Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='run_id', full_name='Slot_Object_Pong.run_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['Slot_Object_Ping'] = _SLOT_OBJECT_PING
DESCRIPTOR.message_types_by_name['Slot_Object_Pong'] = _SLOT_OBJECT_PONG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Slot_Object_Ping = _reflection.GeneratedProtocolMessageType('Slot_Object_Ping', (_message.Message,), {
  'DESCRIPTOR' : _SLOT_OBJECT_PING,
  '__module__' : 'gameslot_pb2'
  # @@protoc_insertion_point(class_scope:Slot_Object_Ping)
  })
_sym_db.RegisterMessage(Slot_Object_Ping)

Slot_Object_Pong = _reflection.GeneratedProtocolMessageType('Slot_Object_Pong', (_message.Message,), {
  'DESCRIPTOR' : _SLOT_OBJECT_PONG,
  '__module__' : 'gameslot_pb2'
  # @@protoc_insertion_point(class_scope:Slot_Object_Pong)
  })
_sym_db.RegisterMessage(Slot_Object_Pong)



_GAMESLOTSERVICE = _descriptor.ServiceDescriptor(
  name='GameSlotService',
  full_name='GameSlotService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=90,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='obtenir_slot_object',
    full_name='GameSlotService.obtenir_slot_object',
    index=0,
    containing_service=None,
    input_type=_SLOT_OBJECT_PING,
    output_type=_SLOT_OBJECT_PONG,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMESLOTSERVICE)

DESCRIPTOR.services_by_name['GameSlotService'] = _GAMESLOTSERVICE

# @@protoc_insertion_point(module_scope)
