# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import gameslot_pb2 as gameslot__pb2


class GameSlotServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.obtenir_slot_object = channel.unary_unary(
        '/GameSlotService/obtenir_slot_object',
        request_serializer=gameslot__pb2.Slot_Object_Ping.SerializeToString,
        response_deserializer=gameslot__pb2.Slot_Object_Pong.FromString,
        )


class GameSlotServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def obtenir_slot_object(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GameSlotServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'obtenir_slot_object': grpc.unary_unary_rpc_method_handler(
          servicer.obtenir_slot_object,
          request_deserializer=gameslot__pb2.Slot_Object_Ping.FromString,
          response_serializer=gameslot__pb2.Slot_Object_Pong.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'GameSlotService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
